# riangular, pentagonal, and hexagonal
# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
import time
from termcolor import colored

def Triangle(i):
    n = i * (i + 1) // 2
    return n


def Pentagonal(i):
    n = i * (3*i - 1) // 2
    return n

def Hexagonal(i):
    n = i *(2*i - 1)
    return n


def main_process():
    for i in range(1,10):
        print('T:(',i,')',Triangle(i))
        print('P:(',i,')',Pentagonal(i))
        print('H:(',i,')',Hexagonal(i))
        print('\n')

    print(colored('mycount=', 'red'), 'results')

if __name__ == "__main__":
    tic = time.clock()
    
    main_process()

    toc = time.clock()
    print("time=",toc - tic)